Make custom backend library to simplify creation of custom backends (#361)

diff --git a/Dockerfile.custombackend b/Dockerfile.custombackend
--- a/Dockerfile.custombackend
+++ b/Dockerfile.custombackend
@@ -24,54 +24,42 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-cmake_minimum_required (VERSION 3.5)
-project (trtis-custom-backends)
+# Default setting is building on ubuntu:16.04
+ARG UBUNTU_VERSION=16.04
 
-if(NOT CMAKE_BUILD_TYPE)
-  set(CMAKE_BUILD_TYPE Release)
-endif()
+FROM ubuntu:${UBUNTU_VERSION}
 
-set(CMAKE_CXX_FLAGS "-Wall -Wextra -Wno-unused-parameter -Werror")
-set(CMAKE_CXX_FLAGS_DEBUG "-g")
-set(CMAKE_CXX_FLAGS_RELEASE "-O3")
-set(CMAKE_CXX_STANDARD 11)
-set(CMAKE_POSITION_INDEPENDENT_CODE ON)
+# Ensure apt-get won't prompt for selecting options
+ENV DEBIAN_FRONTEND=noninteractive
 
-if(${TRTIS_ENABLE_GPU})
-  add_definitions(-DTRTIS_ENABLE_GPU=1)
-endif() # TRTIS_ENABLE_GPU
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends \
+            software-properties-common \
+            build-essential \
+            cmake \
+            git \
+            libopencv-dev \
+            libopencv-core-dev \
+            libssl-dev \
+            libtool \
+            pkg-config
 
-include_directories("${PROJECT_SOURCE_DIR}/../..")
-include_directories("${PROJECT_BINARY_DIR}")
+# Build the custom backend library and example custom backends
+WORKDIR /workspace
+COPY VERSION VERSION
+COPY build build
+COPY src/backends/custom/custom.h src/backends/custom/custom.h
+COPY src/custom src/custom
+COPY src/core src/core
 
-#
-# CUDA
-#
-if(${TRTIS_ENABLE_GPU})
-  find_package(CUDA REQUIRED)
-  message(STATUS "Using CUDA ${CUDA_VERSION}")
-  set(CUDA_NVCC_FLAGS -std=c++11)
-endif() # TRTIS_ENABLE_GPU
-
-#
-# Protobuf
-#
-set(protobuf_MODULE_COMPATIBLE TRUE)
-find_package(Protobuf CONFIG REQUIRED)
-message(STATUS "Using protobuf ${Protobuf_VERSION}")
-include_directories(${Protobuf_INCLUDE_DIRS})
-
-#
-# GRPC
-#
-find_package(gRPC CONFIG REQUIRED)
-message(STATUS "Using gRPC ${gRPC_VERSION}")
-include_directories($<TARGET_PROPERTY:gRPC::grpc,INTERFACE_INCLUDE_DIRECTORIES>)
-
-add_subdirectory(../../src/core src/core)
-add_subdirectory(../../src/custom src/custom)
-add_subdirectory(../../src/custom/addsub src/custom/addsub)
-add_subdirectory(../../src/custom/identity src/custom/identity)
-add_subdirectory(../../src/custom/image_preprocess src/custom/image_preprocess)
-add_subdirectory(../../src/custom/param src/custom/param)
-add_subdirectory(../../src/custom/sequence src/custom/sequence)
+# The build can fail the first time due to a protobuf_generate_cpp
+# error that doesn't repeat on subsequent builds, which is why there
+# are 2 make invocations below.
+RUN (cd build && \
+            cmake -DTRTIS_ENABLE_GPU=OFF \
+                  -DCMAKE_BUILD_TYPE=Release \
+                  -DCMAKE_INSTALL_PREFIX:PATH=/workspace/install && \
+            (make -j16 trtis-custom-backends || true) && \
+            make -j16 trtis-custom-backends) && \
+    export VERSION=`cat /workspace/VERSION` && \
+    (cd install && tar zcf /workspace/v$VERSION.custombackends.tar.gz *)
