Remove bazel and makefile build for clients, use cmake

diff --git a/Dockerfile.client b/Dockerfile.client
--- a/Dockerfile.client
+++ b/Dockerfile.client
@@ -51,10 +51,12 @@ RUN apt-get install -y --no-install-recommends \
             autoconf \
             automake \
             build-essential \
+            cmake \
             curl \
             git \
             libopencv-dev \
             libopencv-core-dev \
+            libssl-dev \
             libtool \
             pkg-config \
             python \
@@ -68,40 +70,20 @@ RUN pip install --upgrade setuptools grpcio-tools
 
 # Build the client library and examples
 WORKDIR /workspace
-COPY Makefile.client .
 COPY VERSION .
-COPY src src
-RUN make -j8 -f Makefile.client all
+COPY build build
+COPY src/clients src/clients
+COPY src/core src/core
 
-# Collect the client artifacts into a tar
-RUN mkdir -p /tmp/client/bin && \
-    cp build/image_client /tmp/client/bin/. && \
-    cp build/ensemble_image_client /tmp/client/bin/. && \
-    cp build/perf_client /tmp/client/bin/. && \
-    cp build/simple_client /tmp/client/bin/. && \
-    cp build/simple_string_client /tmp/client/bin/. && \
-    cp build/simple_sequence_client /tmp/client/bin/. && \
-    mkdir -p /tmp/client/lib && \
-    cp build/librequest.so /tmp/client/lib/. && \
-    cp build/librequest.a /tmp/client/lib/. && \
-    mkdir -p /tmp/client/include && \
-    cp build/src/core/api.pb.h /tmp/client/include/. && \
-    cp build/src/core/model_config.pb.h /tmp/client/include/. && \
-    cp build/src/core/request_status.pb.h /tmp/client/include/. && \
-    cp build/src/core/server_status.pb.h /tmp/client/include/. && \
-    cp src/clients/c++/request.h /tmp/client/include/. && \
-    cp src/clients/c++/request_http.h /tmp/client/include/. && \
-    cp src/clients/c++/request_grpc.h /tmp/client/include/. && \
-    mkdir -p /tmp/client/python && \
-    cp src/clients/python/image_client.py /tmp/client/python/. && \
-    cp src/clients/python/ensemble_image_client.py /tmp/client/python/. && \
-    cp src/clients/python/grpc_image_client.py /tmp/client/python/. && \
-    cp src/clients/python/simple_client.py /tmp/client/python/. && \
-    cp src/clients/python/simple_string_client.py /tmp/client/python/. && \
-    cp src/clients/python/simple_sequence_client.py /tmp/client/python/. && \
-    cp build/dist/dist/*.whl /tmp/client/python/. && \
+# The build can fail the first time due to a protobuf_generate_cpp
+# error that doesn't repeat on subsequent builds, which is why there
+# are 2 make invocations below.
+RUN cd build && \
+    cmake -DCMAKE_BUILD_TYPE=Release && \
+    (make -j8 trtis-clients || true) && \
+    make -j8 trtis-clients && \
     export VERSION=`cat /workspace/VERSION` && \
-    (cd /tmp/client && tar zcf /workspace/v$VERSION.clients.tar.gz *)
+    (cd trtis-clients/install && tar zcf /workspace/v$VERSION.clients.tar.gz *)
 
 # Install an image needed by the quickstart and other documentation.
 COPY qa/images/mug.jpg images/mug.jpg
@@ -109,4 +91,4 @@ COPY qa/images/mug.jpg images/mug.jpg
 # Install the dependencies needed to run the client examples. These
 # are not needed for building but including them allows this image to
 # be used to run the client examples.
-RUN pip install --upgrade build/dist/dist/tensorrtserver-*.whl numpy pillow
+RUN pip install --upgrade build/trtis-clients/install/python/tensorrtserver-*.whl numpy pillow
