Decent progress

diff --git a/qa/common/gen_qa_model_repository_volume b/qa/common/gen_qa_model_repository_volume
--- a/qa/common/gen_qa_model_repository_volume
+++ b/qa/common/gen_qa_model_repository_volume
@@ -66,52 +66,80 @@ CUDA_DEVICE=${NV_GPU:=0}
 DOCKER_GPU_ARGS=${DOCKER_GPU_ARGS:-$([[ $RUNNER_GPUS =~ ^[0-9] ]] && eval $NV_DOCKER_ARGS || echo "--gpus device=$CUDA_DEVICE" )}
 MODEL_TYPE=${MODEL_TYPE:-""}
 
-CI_JOB_ID=${CI_JOB_ID:=$(date +%Y%m%d_%H%M)}
 ############################################################################
 # Check if Docker volume exists
 ############################################################################
+CI_JOB_ID=${CI_JOB_ID:=$(date +%Y%m%d_%H%M)}
 DOCKER_VOLUME=${DOCKER_VOLUME:=volume_gen_qa_model_repositor_${CI_JOB_ID}}
 if ! docker volume inspect $DOCKER_VOLUME > /dev/null 2>&1; then
     echo "Docker volume $DOCKER_VOLUME does not exist. Creating..."
     docker volume create $DOCKER_VOLUME
     docker volume inspect $DOCKER_VOLUME
 fi
-VOLUME_BUILD_DIR=${CI_JOB_ID:=tmp}
-VOLUME_SRCDIR=${VOLUME_SRCDIR:=$VOLUME_BUILD_DIR/gen_srcdir}
 
 docker rm -f $DOCKER_VOLUME
-docker create --name $DOCKER_VOLUME -v $DOCKER_VOLUME:/mnt -w /mnt/$VOLUME_SRCDIR $UBUNTU_IMAGE
-# FIXME: move to the end
-docker cp ../common $DOCKER_VOLUME:/mnt/$VOLUME_BUILD_DIR
+docker run --rm -v $DOCKER_VOLUME:/mnt -w /mnt/$CI_JOB_ID $UBUNTU_IMAGE mkdir -p gen_srcdir ${TRITON_VERSION}
+docker create --name $DOCKER_VOLUME -v $DOCKER_VOLUME:/mnt -w /mnt/$CI_JOB_ID $UBUNTU_IMAGE
+docker cp . $DOCKER_VOLUME:/mnt/$CI_JOB_ID/gen_srcdir
 
-docker run --rm -it  -v $DOCKER_VOLUME:/mnt -w /mnt/$VOLUME_BUILD_DIR/$TRITON_VERSION $UBUNTU_IMAGE \
+VOLUME_BUILD_DIR=${VOLUME_BUILD_DIR:=/mnt/$CI_JOB_ID}
+VOLUME_SRCDIR=${VOLUME_SRCDIR:=$VOLUME_BUILD_DIR/gen_srcdir}
+VOLUME_DESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_model_repository
+VOLUME_VARDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_variable_model_repository
+VOLUME_IDENTITYDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_identity_model_repository
+VOLUME_SIGDEFDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_tf_tag_sigdef_repository
+VOLUME_IDENTITYBIGDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_identity_big_model_repository
+VOLUME_TFPARAMETERSDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_tf_parameters_repository
+VOLUME_SHAPEDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_shapetensor_model_repository
+VOLUME_RESHAPEDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_reshape_model_repository
+VOLUME_SEQDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_sequence_model_repository
+VOLUME_DYNASEQDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_dyna_sequence_model_repository
+VOLUME_DYNASEQIMPLICITDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_dyna_sequence_implicit_model_repository
+VOLUME_VARSEQDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_variable_sequence_model_repository
+VOLUME_ENSEMBLEDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_ensemble_model_repository
+VOLUME_NOSHAPEDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_noshape_model_repository
+VOLUME_PLGDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_trt_plugin_model_repository
+VOLUME_RAGGEDDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_ragged_model_repository
+VOLUME_FORMATDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_trt_format_model_repository
+VOLUME_DATADEPENDENTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_trt_data_dependent_model_repository
+VOLUME_IMPLICITSEQDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_sequence_implicit_model_repository
+VOLUME_VARIMPLICITSEQDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_variable_sequence_implicit_model_repository
+VOLUME_INITIALSTATEIMPLICITSEQDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_sequence_initial_state_implicit_model_repository
+VOLUME_VARINITIALSTATEIMPLICITSEQDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_variable_sequence_initial_state_implicit_model_repository
+VOLUME_TORCHTRTDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/torchtrt_model_store
+VOLUME_SCALARMODELSDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_scalar_models
+VOLUME_IMAGEMODELSDESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_dynamic_batch_image_model_repository
+
+
+docker run --rm -v $DOCKER_VOLUME:/mnt -w /mnt/$CI_JOB_ID $UBUNTU_IMAGE \
 mkdir -p \
-qa_dyna_sequence_implicit_model_repository \
-qa_dyna_sequence_model_repository \
-qa_dynamic_batch_image_model_repository
-qa_ensemble_model_repository \
-qa_identity_big_model_repository \
-qa_identity_model_repository \
-qa_model_repository \
-qa_noshape_model_repository \
-qa_ragged_model_repository \
-qa_reshape_model_repository \
-qa_scalar_models \
-qa_sequence_implicit_model_repository \
-qa_sequence_initial_state_implicit_model_repository \
-qa_sequence_model_repository \
-qa_shapetensor_model_repository \
-qa_tf_parameters_repository \
-qa_tf_tag_sigdef_repository \
-qa_trt_data_dependent_model_repository \
-qa_trt_format_model_repository \
-qa_trt_plugin_model_repository \
-qa_variable_model_repository \
-qa_variable_sequence_implicit_model_repository \
-qa_variable_sequence_initial_state_implicit_model_repository \
-qa_variable_sequence_model_repository \
-torchtrt_model_store
-
+$VOLUME_BUILD_DIR \
+$VOLUME_SRCDIR \
+$VOLUME_DESTDIR \
+$VOLUME_VARDESTDIR \
+$VOLUME_IDENTITYDESTDIR \
+$VOLUME_SIGDEFDESTDIR \
+$VOLUME_IDENTITYBIGDESTDIR \
+$VOLUME_TFPARAMETERSDESTDIR \
+$VOLUME_SHAPEDESTDIR \
+$VOLUME_RESHAPEDESTDIR \
+$VOLUME_SEQDESTDIR \
+$VOLUME_DYNASEQDESTDIR \
+$VOLUME_DYNASEQIMPLICITDESTDIR \
+$VOLUME_VARSEQDESTDIR \
+$VOLUME_ENSEMBLEDESTDIR \
+$VOLUME_NOSHAPEDESTDIR \
+$VOLUME_PLGDESTDIR \
+$VOLUME_RAGGEDDESTDIR \
+$VOLUME_FORMATDESTDIR \
+$VOLUME_DATADEPENDENTDIR \
+$VOLUME_IMPLICITSEQDESTDIR \
+$VOLUME_VARIMPLICITSEQDESTDIR \
+$VOLUME_INITIALSTATEIMPLICITSEQDESTDIR \
+$VOLUME_VARINITIALSTATEIMPLICITSEQDESTDIR \
+$VOLUME_TORCHTRTDESTDIR \
+$VOLUME_SCALARMODELSDESTDIR \
+$VOLUME_IMAGEMODELSDESTDIR
 
 ONNXSCRIPT=onnx_gen.cmds
 OPENVINOSCRIPT=openvino_gen.cmds
@@ -120,11 +148,11 @@ TFSCRIPT=tf_gen.cmds
 TRTSCRIPT=trt_gen.cmds
 
 # OPENVINO
-
-OpenVINO is not available on ARM so skip
+#
+# OpenVINO is not available on ARM so skip
 if [[ "aarch64" != $(uname -m) ]] ; then
 
-cat >../common/$OPENVINOSCRIPT <<EOF
+cat > $OPENVINOSCRIPT <<EOF
 #!/bin/bash
 # Make all generated files accessible outside of container
 umask 0000
@@ -146,37 +174,29 @@ pip3 install openvino==$OPENVINO_VERSION
 # Since variable shape tensors are not allowed, identity models may fail to generate.
 # TODO Add variable size tensor models after DLIS-2827 adds support for variable shape tensors.
 # TODO Add sequence models after DLIS-2864 adds support for sequence/control inputs.
-python3 $SRCDIR/gen_qa_models.py --openvino --models_dir=$DESTDIR
-chmod -R 777 $DESTDIR
-# python3 $SRCDIR/gen_qa_identity_models.py --openvino --models_dir=$IDENTITYDESTDIR
-# chmod -R 777 $IDENTITYDESTDIR
-python3 $SRCDIR/gen_qa_reshape_models.py --openvino --models_dir=$RESHAPEDESTDIR
-chmod -R 777 $RESHAPEDESTDIR
-# python3 $SRCDIR/gen_qa_sequence_models.py --openvino --models_dir=$SEQDESTDIR
-# chmod -R 777 $SEQDESTDIR
-# python3 $SRCDIR/gen_qa_dyna_sequence_models.py --openvino --models_dir=$DYNASEQDESTDIR
-# chmod -R 777 $DYNASEQDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_models.py --openvino --models_dir=$VOLUME_DESTDIR
+chmod -R 777 $VOLUME_DESTDIR
+# python3 $VOLUME_SRCDIR/gen_qa_identity_models.py --openvino --models_dir=$VOLUME_IDENTITYDESTDIR
+# chmod -R 777 $VOLUME_IDENTITYDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_reshape_models.py --openvino --models_dir=$VOLUME_RESHAPEDESTDIR
+chmod -R 777 $VOLUME_RESHAPEDESTDIR
+# python3 $VOLUME_SRCDIR/gen_qa_sequence_models.py --openvino --models_dir=$VOLUME_SEQDESTDIR
+# chmod -R 777 $SVOLUME_EQDESTDIR
+# python3 $VOLUME_SRCDIR/gen_qa_dyna_sequence_models.py --openvino --models_dir=$VOLUME_DYNASEQDESTDIR
+# chmod -R 777 $VOLUME_DYNASEQDESTDIR
 EOF
 
-chmod a+x $VOLUME_SRCDIR/$OPENVINOSCRIPT
+chmod a+x $OPENVINOSCRIPT
 if [ $? -ne 0 ]; then
     echo -e "Failed: chmod"
     exit 1
 fi
 
+docker cp $OPENVINOSCRIPT $DOCKER_VOLUME:$VOLUME_SRCDIR
+
 docker pull $UBUNTU_IMAGE
-docker run $DOCKER_GPU_ARGS --rm --entrypoint $SRCDIR/$OPENVINOSCRIPT \
-       --mount type=bind,source=$VOLUME_SRCDIR,target=$SRCDIR \
-       --mount type=bind,source=$VOLUME_DESTDIR,target=$DESTDIR \
-       --mount type=bind,source=$VOLUME_VARDESTDIR,target=$VARDESTDIR \
-       --mount type=bind,source=$VOLUME_IDENTITYDESTDIR,target=$IDENTITYDESTDIR \
-       --mount type=bind,source=$VOLUME_RESHAPEDESTDIR,target=$RESHAPEDESTDIR \
-       --mount type=bind,source=$VOLUME_SEQDESTDIR,target=$SEQDESTDIR \
-       --mount type=bind,source=$VOLUME_DYNASEQDESTDIR,target=$DYNASEQDESTDIR \
-       --mount type=bind,source=$VOLUME_VARSEQDESTDIR,target=$VARSEQDESTDIR \
-       --mount type=bind,source=$VOLUME_RAGGEDDESTDIR,target=$RAGGEDDESTDIR \
-       --mount type=bind,source=$VOLUME_SCALARMODELSDESTDIR,target=$SCALARMODELSDESTDIR \
-       $UBUNTU_IMAGE
+docker run $DOCKER_GPU_ARGS --rm -v $DOCKER_VOLUME:/mnt $UBUNTU_IMAGE bash -xe $VOLUME_SRCDIR/$OPENVINOSCRIPT
+
 if [ $? -ne 0 ]; then
     echo -e "Failed"
     exit 1
@@ -184,82 +204,68 @@ fi
 
 fi # [[ "aarch64" != $(uname -m) ]]
 
-# # ONNX
-# cat >$VOLUME_SRCDIR/$ONNXSCRIPT <<EOF
-# #!/bin/bash
-# # Make all generated files accessible outside of container
-# umask 0000
-# nvidia-smi -L || true
-# nvidia-smi || true
-# set -e
-# set -x
-# export DEBIAN_FRONTEND=noninteractive
-# apt-get update && \
-#         apt-get install -y --no-install-recommends build-essential cmake libprotobuf-dev \
-#                 protobuf-compiler python3 python3-dev python3-pip
-# ln -s /usr/bin/python3 /usr/bin/python
+# ONNX
+cat > $ONNXSCRIPT <<EOF
+#!/bin/bash
+# Make all generated files accessible outside of container
+umask 0000
+nvidia-smi -L || true
+nvidia-smi || true
+set -e
+set -x
+export DEBIAN_FRONTEND=noninteractive
+apt-get update && \
+        apt-get install -y --no-install-recommends build-essential cmake libprotobuf-dev \
+                protobuf-compiler python3 python3-dev python3-pip
+ln -s /usr/bin/python3 /usr/bin/python
 
-# pip3 install "protobuf<=3.20.1"  "numpy<=1.23.5" # TODO: Remove current line DLIS-3838
-# pip3 install --upgrade onnx==${ONNX_VERSION}
+pip3 install "protobuf<=3.20.1"  "numpy<=1.23.5" # TODO: Remove current line DLIS-3838
+pip3 install --upgrade onnx==${ONNX_VERSION}
 
-# python3 $SRCDIR/gen_qa_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$DESTDIR
-# chmod -R 777 $DESTDIR
-# python3 $SRCDIR/gen_qa_models.py --onnx --onnx_opset=$ONNX_OPSET --variable --models_dir=$VARDESTDIR
-# chmod -R 777 $VARDESTDIR
-# python3 $SRCDIR/gen_qa_identity_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$IDENTITYDESTDIR
-# chmod -R 777 $IDENTITYDESTDIR
-# python3 $SRCDIR/gen_qa_reshape_models.py --onnx --onnx_opset=$ONNX_OPSET --variable --models_dir=$RESHAPEDESTDIR
-# chmod -R 777 $RESHAPEDESTDIR
-# python3 $SRCDIR/gen_qa_sequence_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$SEQDESTDIR
-# chmod -R 777 $SEQDESTDIR
-# python3 $SRCDIR/gen_qa_sequence_models.py --onnx --onnx_opset=$ONNX_OPSET --variable --models_dir=$VARSEQDESTDIR
-# chmod -R 777 $VARSEQDESTDIR
-# python3 $SRCDIR/gen_qa_implicit_models.py --onnx --initial-state zero --onnx_opset=$ONNX_OPSET --models_dir=$INITIALSTATEIMPLICITSEQDESTDIR
-# chmod -R 777 $INITIALSTATEIMPLICITSEQDESTDIR
-# python3 $SRCDIR/gen_qa_implicit_models.py --onnx --initial-state zero --onnx_opset=$ONNX_OPSET --variable --models_dir=$VARINITIALSTATEIMPLICITSEQDESTDIR
-# chmod -R 777 $VARINITIALSTATEIMPLICITSEQDESTDIR
-# python3 $SRCDIR/gen_qa_implicit_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$IMPLICITSEQDESTDIR
-# chmod -R 777 $IMPLICITSEQDESTDIR
-# python3 $SRCDIR/gen_qa_implicit_models.py --onnx --onnx_opset=$ONNX_OPSET --variable --models_dir=$VARIMPLICITSEQDESTDIR
-# chmod -R 777 $VARIMPLICITSEQDESTDIR
-# python3 $SRCDIR/gen_qa_dyna_sequence_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$DYNASEQDESTDIR
-# chmod -R 777 $DYNASEQDESTDIR
-# python3 $SRCDIR/gen_qa_dyna_sequence_implicit_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$DYNASEQIMPLICITDESTDIR
-# chmod -R 777 $DYNASEQIMPLICITDESTDIR
-# python3 $SRCDIR/gen_qa_ragged_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$RAGGEDDESTDIR
-# chmod -R 777 $RAGGEDDESTDIR
-# python3 $SRCDIR/gen_qa_ort_scalar_models.py --onnx_opset=$ONNX_OPSET --models_dir=$SCALARMODELSDESTDIR
-# chmod -R 777 $RAGGEDDESTDIR
-# EOF
+python3 $VOLUME_SRCDIR/gen_qa_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$VOLUME_DESTDIR
+chmod -R 777 $VOLUME_DESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_models.py --onnx --onnx_opset=$ONNX_OPSET --variable --models_dir=$VOLUME_VARDESTDIR
+chmod -R 777 $VOLUME_VARDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_identity_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$VOLUME_IDENTITYDESTDIR
+chmod -R 777 $VOLUME_IDENTITYDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_reshape_models.py --onnx --onnx_opset=$ONNX_OPSET --variable --models_dir=$VOLUME_RESHAPEDESTDIR
+chmod -R 777 $VOLUME_RESHAPEDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_sequence_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$VOLUME_SEQDESTDIR
+chmod -R 777 $SEQDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_sequence_models.py --onnx --onnx_opset=$ONNX_OPSET --variable --models_dir=$VOLUME_VARSEQDESTDIR
+chmod -R 777 $VOLUME_VARSEQDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_implicit_models.py --onnx --initial-state zero --onnx_opset=$ONNX_OPSET --models_dir=$VOLUME_INITIALSTATEIMPLICITSEQDESTDIR
+chmod -R 777 $VOLUME_INITIALSTATEIMPLICITSEQDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_implicit_models.py --onnx --initial-state zero --onnx_opset=$ONNX_OPSET --variable --models_dir=$VOLUME_VARINITIALSTATEIMPLICITSEQDESTDIR
+chmod -R 777 $VOLUME_VARINITIALSTATEIMPLICITSEQDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_implicit_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$VOLUME_IMPLICITSEQDESTDIR
+chmod -R 777 $VOLUME_IMPLICITSEQDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_implicit_models.py --onnx --onnx_opset=$ONNX_OPSET --variable --models_dir=$VOLUME_VARIMPLICITSEQDESTDIR
+chmod -R 777 $VOLUME_VARIMPLICITSEQDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_dyna_sequence_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$VOLUME_DYNASEQDESTDIR
+chmod -R 777 $VOLUME_DYNASEQDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_dyna_sequence_implicit_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$DVOLUME_YNASEQIMPLICITDESTDIR
+chmod -R 777 $VOLUME_DYNASEQIMPLICITDESTDIR
+python3 $VOLUME_SRCDIR/gen_qa_ragged_models.py --onnx --onnx_opset=$ONNX_OPSET --models_dir=$VOLUME_RAGGEDDESTDIR
+chmod -R 777 $RAGGEDDESTDIR
+python3 $VOLUME_VOLUME_SRCDIR/gen_qa_ort_scalar_models.py --onnx_opset=$ONNX_OPSET --models_dir=$SCALARMODELSDESTDIR
+chmod -R 777 $VOLUME_RAGGEDDESTDIR
+EOF
 
-# chmod a+x $VOLUME_SRCDIR/$ONNXSCRIPT
-# if [ $? -ne 0 ]; then
-#     echo -e "Failed: chmod"
-#     exit 1
-# fi
+chmod a+x $ONNXSCRIPT
+if [ $? -ne 0 ]; then
+    echo -e "Failed: chmod"
+    exit 1
+fi
 
-# docker pull $UBUNTU_IMAGE
-# docker run $DOCKER_GPU_ARGS --rm --entrypoint $SRCDIR/$ONNXSCRIPT \
-#        --mount type=bind,source=$VOLUME_SRCDIR,target=$SRCDIR \
-#        --mount type=bind,source=$VOLUME_DESTDIR,target=$DESTDIR \
-#        --mount type=bind,source=$VOLUME_VARDESTDIR,target=$VARDESTDIR \
-#        --mount type=bind,source=$VOLUME_IDENTITYDESTDIR,target=$IDENTITYDESTDIR \
-#        --mount type=bind,source=$VOLUME_RESHAPEDESTDIR,target=$RESHAPEDESTDIR \
-#        --mount type=bind,source=$VOLUME_SEQDESTDIR,target=$SEQDESTDIR \
-#        --mount type=bind,source=$VOLUME_DYNASEQDESTDIR,target=$DYNASEQDESTDIR \
-#        --mount type=bind,source=$VOLUME_DYNASEQIMPLICITDESTDIR,target=$DYNASEQIMPLICITDESTDIR \
-#        --mount type=bind,source=$VOLUME_VARSEQDESTDIR,target=$VARSEQDESTDIR \
-#        --mount type=bind,source=$VOLUME_RAGGEDDESTDIR,target=$RAGGEDDESTDIR \
-#        --mount type=bind,source=$VOLUME_VARIMPLICITSEQDESTDIR,target=$VARIMPLICITSEQDESTDIR \
-#        --mount type=bind,source=$VOLUME_IMPLICITSEQDESTDIR,target=$IMPLICITSEQDESTDIR \
-#        --mount type=bind,source=$VOLUME_VARINITIALSTATEIMPLICITSEQDESTDIR,target=$VARINITIALSTATEIMPLICITSEQDESTDIR \
-#        --mount type=bind,source=$VOLUME_INITIALSTATEIMPLICITSEQDESTDIR,target=$INITIALSTATEIMPLICITSEQDESTDIR \
-#        --mount type=bind,source=$VOLUME_SCALARMODELSDESTDIR,target=$SCALARMODELSDESTDIR \
-#        $UBUNTU_IMAGE
-# if [ $? -ne 0 ]; then
-#     echo -e "Failed"
-#     exit 1
-# fi
+docker cp $ONNXSCRIPT $DOCKER_VOLUME:$VOLUME_SRCDIR
+
+docker pull $UBUNTU_IMAGE
+docker run $DOCKER_GPU_ARGS --rm -v $DOCKER_VOLUME:/mnt $UBUNTU_IMAGE bash -xe $VOLUME_SRCDIR/$ONNXSCRIPT
+if [ $? -ne 0 ]; then
+    echo -e "Failed"
+    exit 1
+fi
 
 # # PyTorch
 # cat >$VOLUME_SRCDIR/$TORCHSCRIPT <<EOF
