fix condition

diff --git a/qa/common/gen_qa_model_repository b/qa/common/gen_qa_model_repository
--- a/qa/common/gen_qa_model_repository
+++ b/qa/common/gen_qa_model_repository
@@ -537,8 +537,9 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-[ "$MODEL_TYPE" != "igpu" ] && docker pull $TENSORRT_IMAGE
-[ "$MODEL_TYPE" != "igpu" ] && docker run $DOCKER_GPU_ARGS --rm --entrypoint $SRCDIR/$TRTSCRIPT \
+if [ "$MODEL_TYPE" != "igpu" ] ; then
+docker pull $TENSORRT_IMAGE
+docker run $DOCKER_GPU_ARGS --rm --entrypoint $SRCDIR/$TRTSCRIPT \
        --mount type=bind,source=$HOST_SRCDIR,target=$SRCDIR \
        --mount type=bind,source=$HOST_DESTDIR,target=$DESTDIR \
        --mount type=bind,source=$HOST_VARDESTDIR,target=$VARDESTDIR \
@@ -558,7 +559,9 @@ fi
        --mount type=bind,source=$HOST_IMPLICITSEQDESTDIR,target=$IMPLICITSEQDESTDIR \
        $TENSORRT_IMAGE
 
-if [ $? -ne 0 ]; then
-    echo -e "Failed"
-    exit 1
+  if [ $? -ne 0 ]; then
+      echo -e "Failed"
+      exit 1
+  fi
+
 fi
