Add pytorch custom op model test (#1031)
* create pytorch custom op model

* Add pytorch custom op model to gen_custom_ops

* Add pytorch custom op test

* Fix LD_PRELOAD error

* review edits

* Fix gen_qa_custom_ops script

* Fix L0_tf_multi_stream failure

* Add Pytorch custom ops docs.

diff --git a/qa/common/gen_qa_custom_ops b/qa/common/gen_qa_custom_ops
--- a/qa/common/gen_qa_custom_ops
+++ b/qa/common/gen_qa_custom_ops
@@ -30,8 +30,8 @@
 ## tensorrtserver CI tests. Generating these custom operations
 ## requires using the TensorFlow container.
 ##
-## 1. Update TENSORFLOW_IMAGE to match what is being used by the
-## tensorrtserver release being tested.
+## 1. Update TENSORFLOW_IMAGE and PYTORCH_IMAGE to match what is being used
+## by the tensorrtserver release being tested.
 ##
 ## 2. Run this script to create /tmp/qa_custom_ops.
 ##
@@ -39,6 +39,7 @@
 
 TRTIS_VERSION=19.12
 TENSORFLOW_IMAGE=${TENSORFLOW_IMAGE:=nvcr.io/nvidia/tensorflow:$TRTIS_VERSION-tf1-py3}
+PYTORCH_IMAGE=${PYTORCH_IMAGE:=nvcr.io/nvidia/pytorch:$TRTIS_VERSION-py3}
 
 CUDA_DEVICE=0
 
@@ -47,7 +48,7 @@ HOST_SRCDIR=/tmp/gen_srcdir
 HOST_DESTDIR=/tmp/$TRTIS_VERSION/qa_custom_ops
 
 rm -fr $HOST_DESTDIR
-mkdir -p $HOST_DESTDIR
+mkdir -p $HOST_DESTDIR/tf_custom_ops $HOST_DESTDIR/libtorch_custom_ops
 
 rm -fr $HOST_SRCDIR
 mkdir -p $HOST_SRCDIR
@@ -56,6 +57,7 @@ cp ./gen_qa_custom_ops_models.py $HOST_SRCDIR/.
 cp ./cuda_op_kernel.cu.cc.patch $HOST_SRCDIR/.
 cp ./busy_op_kernel.* $HOST_SRCDIR/.
 TFSCRIPT=tf_gen.cmds
+PYTSCRIPT=pyt_gen.cmds
 
 SRCDIR=/tmp/src
 DESTDIR=/tmp/custom_ops
@@ -102,8 +104,37 @@ fi
 docker pull $TENSORFLOW_IMAGE
 docker run --gpus=1 --rm --entrypoint $SRCDIR/$TFSCRIPT \
        --mount type=bind,source=$HOST_SRCDIR,target=$SRCDIR \
-       --mount type=bind,source=$HOST_DESTDIR,target=$DESTDIR \
+       --mount type=bind,source=$HOST_DESTDIR/tf_custom_ops,target=$DESTDIR \
        $TENSORFLOW_IMAGE
+if [ $? -ne 0 ]; then
+    echo -e "Failed"
+    exit 1
+fi
+
+# PyTorch
+cat >$HOST_SRCDIR/$PYTSCRIPT <<EOF
+#!/bin/bash -x
+set -e
+
+export CUDA_VISIBLE_DEVICES=$CUDA_DEVICE
+
+python3 $SRCDIR/gen_qa_custom_ops_models.py --libtorch --models_dir=$DESTDIR
+chown -R $(id -u):$(id -g) $DESTDIR
+
+cp /tmp/torch_extensions/custom_modulo/custom_modulo.so $DESTDIR/libtorch_modulo/.
+EOF
+
+chmod a+x $HOST_SRCDIR/$PYTSCRIPT
+if [ $? -ne 0 ]; then
+    echo -e "Failed: chmod"
+    exit 1
+fi
+
+docker pull $PYTORCH_IMAGE
+docker run --gpus=1 --rm --entrypoint $SRCDIR/$PYTSCRIPT \
+       --mount type=bind,source=$HOST_SRCDIR,target=$SRCDIR \
+       --mount type=bind,source=$HOST_DESTDIR/libtorch_custom_ops,target=$DESTDIR \
+       -u $(id -u):$(id -g) $PYTORCH_IMAGE
 if [ $? -ne 0 ]; then
     echo -e "Failed"
     exit 1
