Commenting OpenVINO

diff --git a/qa/common/gen_qa_model_repository b/qa/common/gen_qa_model_repository
--- a/qa/common/gen_qa_model_repository
+++ b/qa/common/gen_qa_model_repository
@@ -186,77 +186,77 @@ FORMATDESTDIR=/tmp/formatmodels
 DATADEPENDENTDIR=/tmp/datadependentmodels
 TORCHTRTDESTDIR=/tmp/torchtrtmodels
 
-# OPENVINO
-#
-# OpenVINO is not available on ARM so skip
-if [[ "aarch64" != $(uname -m) ]] ; then
+# # OPENVINO
+# #
+# # OpenVINO is not available on ARM so skip
+# if [[ "aarch64" != $(uname -m) ]] ; then
 
-cat >$HOST_SRCDIR/$OPENVINOSCRIPT <<EOF
-#!/bin/bash
-nvidia-smi -L || true
-nvidia-smi || true
-set -e
-set -x
-export DEBIAN_FRONTEND=noninteractive
-apt-get update && \
-    apt-get install -y --no-install-recommends build-essential cmake libprotobuf-dev \
-            protobuf-compiler python3 python3-dev python3-pip wget gnupg2 \
-            software-properties-common
-ln -s /usr/bin/python3 /usr/bin/python
+# cat >$HOST_SRCDIR/$OPENVINOSCRIPT <<EOF
+# #!/bin/bash
+# nvidia-smi -L || true
+# nvidia-smi || true
+# set -e
+# set -x
+# export DEBIAN_FRONTEND=noninteractive
+# apt-get update && \
+#     apt-get install -y --no-install-recommends build-essential cmake libprotobuf-dev \
+#             protobuf-compiler python3 python3-dev python3-pip wget gnupg2 \
+#             software-properties-common
+# ln -s /usr/bin/python3 /usr/bin/python
 
-(wget https://apt.repos.intel.com/openvino/2021/GPG-PUB-KEY-INTEL-OPENVINO-2021 && \
-    apt-key add GPG-PUB-KEY-INTEL-OPENVINO-2021 && rm GPG-PUB-KEY-INTEL-OPENVINO-2021 && \
-    cd /etc/apt/sources.list.d && \
-    echo "deb https://apt.repos.intel.com/openvino/2021 all main">intel-openvino-2021.list && \
-    apt update && \
-    apt install -y intel-openvino-dev-ubuntu20-${OPENVINO_VERSION})
+# (wget https://apt.repos.intel.com/openvino/2021/GPG-PUB-KEY-INTEL-OPENVINO-2021 && \
+#     apt-key add GPG-PUB-KEY-INTEL-OPENVINO-2021 && rm GPG-PUB-KEY-INTEL-OPENVINO-2021 && \
+#     cd /etc/apt/sources.list.d && \
+#     echo "deb https://apt.repos.intel.com/openvino/2021 all main">intel-openvino-2021.list && \
+#     apt update && \
+#     apt install -y intel-openvino-dev-ubuntu20-${OPENVINO_VERSION})
 
-pip3 install "protobuf<=3.20.1" # TODO: Remove current line DLIS-3838
+# pip3 install "protobuf<=3.20.1" # TODO: Remove current line DLIS-3838
 
-pip3 install  "numpy<=1.23.5" setuptools
+# pip3 install  "numpy<=1.23.5" setuptools
 
-PYTHONPATH=/opt/intel/openvino_${OPENVINO_VERSION}/python/python3
-source /opt/intel/openvino_${OPENVINO_VERSION}/bin/setupvars.sh .
+# PYTHONPATH=/opt/intel/openvino_${OPENVINO_VERSION}/python/python3
+# source /opt/intel/openvino_${OPENVINO_VERSION}/bin/setupvars.sh .
 
-# Since variable shape tensors are not allowed, identity models may fail to generate.
-# TODO Add variable size tensor models after DLIS-2827 adds support for variable shape tensors.
-# TODO Add sequence models after DLIS-2864 adds support for sequence/control inputs.
-python3 $SRCDIR/gen_qa_models.py --openvino --models_dir=$DESTDIR
-chmod -R 777 $DESTDIR
-# python3 $SRCDIR/gen_qa_identity_models.py --openvino --models_dir=$IDENTITYDESTDIR
-# chmod -R 777 $IDENTITYDESTDIR
-python3 $SRCDIR/gen_qa_reshape_models.py --openvino --models_dir=$RESHAPEDESTDIR
-chmod -R 777 $RESHAPEDESTDIR
-# python3 $SRCDIR/gen_qa_sequence_models.py --openvino --models_dir=$SEQDESTDIR
-# chmod -R 777 $SEQDESTDIR
-# python3 $SRCDIR/gen_qa_dyna_sequence_models.py --openvino --models_dir=$DYNASEQDESTDIR
-# chmod -R 777 $DYNASEQDESTDIR
-EOF
+# # Since variable shape tensors are not allowed, identity models may fail to generate.
+# # TODO Add variable size tensor models after DLIS-2827 adds support for variable shape tensors.
+# # TODO Add sequence models after DLIS-2864 adds support for sequence/control inputs.
+# python3 $SRCDIR/gen_qa_models.py --openvino --models_dir=$DESTDIR
+# chmod -R 777 $DESTDIR
+# # python3 $SRCDIR/gen_qa_identity_models.py --openvino --models_dir=$IDENTITYDESTDIR
+# # chmod -R 777 $IDENTITYDESTDIR
+# python3 $SRCDIR/gen_qa_reshape_models.py --openvino --models_dir=$RESHAPEDESTDIR
+# chmod -R 777 $RESHAPEDESTDIR
+# # python3 $SRCDIR/gen_qa_sequence_models.py --openvino --models_dir=$SEQDESTDIR
+# # chmod -R 777 $SEQDESTDIR
+# # python3 $SRCDIR/gen_qa_dyna_sequence_models.py --openvino --models_dir=$DYNASEQDESTDIR
+# # chmod -R 777 $DYNASEQDESTDIR
+# EOF
 
-chmod a+x $HOST_SRCDIR/$OPENVINOSCRIPT
-if [ $? -ne 0 ]; then
-    echo -e "Failed: chmod"
-    exit 1
-fi
+# chmod a+x $HOST_SRCDIR/$OPENVINOSCRIPT
+# if [ $? -ne 0 ]; then
+#     echo -e "Failed: chmod"
+#     exit 1
+# fi
 
-docker pull $UBUNTU_IMAGE
-docker run $DOCKER_GPU_ARGS --rm --entrypoint $SRCDIR/$OPENVINOSCRIPT \
-       --mount type=bind,source=$HOST_SRCDIR,target=$SRCDIR \
-       --mount type=bind,source=$HOST_DESTDIR,target=$DESTDIR \
-       --mount type=bind,source=$HOST_VARDESTDIR,target=$VARDESTDIR \
-       --mount type=bind,source=$HOST_IDENTITYDESTDIR,target=$IDENTITYDESTDIR \
-       --mount type=bind,source=$HOST_RESHAPEDESTDIR,target=$RESHAPEDESTDIR \
-       --mount type=bind,source=$HOST_SEQDESTDIR,target=$SEQDESTDIR \
-       --mount type=bind,source=$HOST_DYNASEQDESTDIR,target=$DYNASEQDESTDIR \
-       --mount type=bind,source=$HOST_VARSEQDESTDIR,target=$VARSEQDESTDIR \
-       --mount type=bind,source=$HOST_RAGGEDDESTDIR,target=$RAGGEDDESTDIR \
-       $UBUNTU_IMAGE
-if [ $? -ne 0 ]; then
-    echo -e "Failed"
-    exit 1
-fi
+# docker pull $UBUNTU_IMAGE
+# docker run $DOCKER_GPU_ARGS --rm --entrypoint $SRCDIR/$OPENVINOSCRIPT \
+#        --mount type=bind,source=$HOST_SRCDIR,target=$SRCDIR \
+#        --mount type=bind,source=$HOST_DESTDIR,target=$DESTDIR \
+#        --mount type=bind,source=$HOST_VARDESTDIR,target=$VARDESTDIR \
+#        --mount type=bind,source=$HOST_IDENTITYDESTDIR,target=$IDENTITYDESTDIR \
+#        --mount type=bind,source=$HOST_RESHAPEDESTDIR,target=$RESHAPEDESTDIR \
+#        --mount type=bind,source=$HOST_SEQDESTDIR,target=$SEQDESTDIR \
+#        --mount type=bind,source=$HOST_DYNASEQDESTDIR,target=$DYNASEQDESTDIR \
+#        --mount type=bind,source=$HOST_VARSEQDESTDIR,target=$VARSEQDESTDIR \
+#        --mount type=bind,source=$HOST_RAGGEDDESTDIR,target=$RAGGEDDESTDIR \
+#        $UBUNTU_IMAGE
+# if [ $? -ne 0 ]; then
+#     echo -e "Failed"
+#     exit 1
+# fi
 
-fi # [[ "aarch64" != $(uname -m) ]]
+# fi # [[ "aarch64" != $(uname -m) ]]
 
 # ONNX
 cat >$HOST_SRCDIR/$ONNXSCRIPT <<EOF
